-- Esquema de tabla para análisis de reuniones Farmer Mass
-- Base de datos: FIVETRAN
-- Schema: PUBLIC (o el configurado)

CREATE TABLE IF NOT EXISTS FARMER_MASS_MEETING_ANALYSIS (
    -- Identificación única
    ID VARCHAR(100) PRIMARY KEY,
    
    -- Participantes
    ALIADO_NAME VARCHAR(500),
    FARMER_NAME VARCHAR(500),
    HUNTER_NAME VARCHAR(500),
    
    -- Información de la reunión
    FECHA_REUNION VARCHAR(100),
    DURACION_MINUTOS NUMBER,
    TIPO_REUNION VARCHAR(100),
    
    -- Evaluación de habilidades del Farmer (0-10)
    CLARIDAD_PITCH NUMBER,
    NEGOCIACION_HABILIDADES NUMBER,
    RESOLUCION_OBJECCIONES NUMBER,
    FOLLOWUP_COMPROMISOS VARIANT,  -- Array JSON
    
    -- Evaluación del cliente/aliado
    NIVEL_INTERES_CLIENTE VARCHAR(100),
    OBJECIONES_PRINCIPALES VARIANT,  -- Array JSON
    NECESIDADES_DETECTADAS VARIANT,  -- Array JSON
    DECISION_MAKER_IDENTIFICADO VARCHAR(50),
    NOMBRE_DECISION_MAKER VARCHAR(500),
    
    -- Scoring y próximos pasos
    PROBABILIDAD_CIERRE NUMBER,  -- 0-100
    NEXT_STEPS VARIANT,  -- Array JSON
    RIESGOS VARIANT,  -- Array JSON
    
    -- Metadata y resumen
    RESUMEN_BREVE VARCHAR(5000),
    TEMAS_NO_MENCIONADOS VARIANT,  -- Array JSON
    LINK_DOCUMENTO VARCHAR(1000),
    FOLDER_ID VARCHAR(200),
    DOCUMENT_ID VARCHAR(200),
    FECHA_PROCESAMIENTO TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    -- JSON completo del análisis
    ANALISIS_COMPLETO_JSON VARIANT
);

-- Índices para mejorar performance de consultas
CREATE INDEX IF NOT EXISTS IDX_DOCUMENT_ID ON FARMER_MASS_MEETING_ANALYSIS(DOCUMENT_ID);
CREATE INDEX IF NOT EXISTS IDX_FARMER_NAME ON FARMER_MASS_MEETING_ANALYSIS(FARMER_NAME);
CREATE INDEX IF NOT EXISTS IDX_FECHA_PROCESAMIENTO ON FARMER_MASS_MEETING_ANALYSIS(FECHA_PROCESAMIENTO);

-- Vista para análisis agregado por Farmer
CREATE OR REPLACE VIEW VW_FARMER_PERFORMANCE AS
SELECT 
    FARMER_NAME,
    COUNT(*) AS TOTAL_REUNIONES,
    AVG(CLARIDAD_PITCH) AS AVG_CLARIDAD_PITCH,
    AVG(NEGOCIACION_HABILIDADES) AS AVG_NEGOCIACION,
    AVG(RESOLUCION_OBJECCIONES) AS AVG_RESOLUCION_OBJECCIONES,
    AVG(PROBABILIDAD_CIERRE) AS AVG_PROBABILIDAD_CIERRE,
    SUM(CASE WHEN PROBABILIDAD_CIERRE >= 70 THEN 1 ELSE 0 END) AS REUNIONES_ALTA_PROBABILIDAD,
    MAX(FECHA_PROCESAMIENTO) AS ULTIMA_REUNION
FROM FARMER_MASS_MEETING_ANALYSIS
GROUP BY FARMER_NAME;

-- Vista para análisis de hitos cumplidos
CREATE OR REPLACE VIEW VW_HITOS_CUMPLIMIENTO AS
SELECT 
    ID,
    FARMER_NAME,
    ALIADO_NAME,
    FECHA_REUNION,
    CLARIDAD_PITCH >= 7 AS HITO_CLARIDAD_CUMPLIDO,
    NEGOCIACION_HABILIDADES >= 7 AS HITO_NEGOCIACION_CUMPLIDO,
    RESOLUCION_OBJECCIONES >= 7 AS HITO_RESOLUCION_CUMPLIDO,
    DECISION_MAKER_IDENTIFICADO = 'Sí' AS HITO_DECISION_MAKER_CUMPLIDO,
    PROBABILIDAD_CIERRE >= 70 AS ALTA_PROBABILIDAD_CIERRE
FROM FARMER_MASS_MEETING_ANALYSIS;

-- Consulta de ejemplo: Top Farmers por desempeño
SELECT 
    FARMER_NAME,
    TOTAL_REUNIONES,
    ROUND(AVG_CLARIDAD_PITCH, 2) AS CLARIDAD,
    ROUND(AVG_NEGOCIACION, 2) AS NEGOCIACION,
    ROUND(AVG_PROBABILIDAD_CIERRE, 2) AS PROB_CIERRE,
    REUNIONES_ALTA_PROBABILIDAD
FROM VW_FARMER_PERFORMANCE
WHERE TOTAL_REUNIONES >= 5
ORDER BY AVG_PROBABILIDAD_CIERRE DESC
LIMIT 10;
